### ISSUE TITLE
Use `__main__`?

### ISSUE THREAD

**Issue by cool-RR** [Nurdok/spanreed#5]
I noticed you have a file `spanreed_main.py`. Why not call it `__main__.py`? Then you could just run `python -m spanreed`.

**Comment by Nurdok** [comment]
Done, thanks.

**Comment by cool-RR** [comment]
I think the `__main__` file is supposed to be _in_ the package rather than outside of it for it to work. ([Example](https://github.com/cool-RR/fruit_slots/tree/master/fruit_slots).) But I'm guessing you don't use `-m` to run your module so it probably doesn't matter to you.

**Comment by Nurdok** [comment]
Right you are. Fixed. Thanks.
